language: ruby

rvm:

- 2.6.0

bundler_args: --jobs 1 --retry 3

script:
  - bin/rake db:create RAILS_ENV=test
  - bin/rake db:migrate RAILS_ENV=test

  - rspec

cache: bundler

services:
  - postgresql

before_script:
  - psql -c 'create database interview_5xruby_test;' -U postgres